<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Fund Request Rejected</title>
</head>

<body style="font-family: Arial, Helvetica, sans-serif; background:#f4f6f9; padding:30px;">

    <table width="650" align="center" cellpadding="0" cellspacing="0"
        style="background:#ffffff;border-radius:8px;overflow:hidden;border:1px solid #dddddd;">

        <tr>
            <td style="background:#dc3545;color:#ffffff;padding:20px;text-align:center;">
                <h2 style="margin:0;">Fund Request Rejected</h2>
            </td>
        </tr>

        <tr>
            <td style="padding:30px;">

                <p>Dear <strong>{{ $fundRequest->user->name }}</strong>,</p>

                <p>
                    We would like to inform you that your Fund Request has been
                    <strong style="color:#dc3545;">rejected</strong>
                    after review.
                </p>

                <table width="100%" cellpadding="8" style="border-collapse:collapse;margin:20px 0;">

                    <tr style="background:#f8f9fa;">
                        <td width="180"><strong>Request Title</strong></td>
                        <td>{{ $fundRequest->title }}</td>
                    </tr>

                    <tr>
                        <td><strong>Request Date</strong></td>
                        <td>{{ \Carbon\Carbon::parse($fundRequest->request_date)->format('d M Y') }}</td>
                    </tr>

                    <tr style="background:#f8f9fa;">
                        <td><strong>Status</strong></td>
                        <td>
                            <span style="color:#dc3545;font-weight:bold;">
                                Rejected
                            </span>
                        </td>
                    </tr>

                    <tr>
                        <td><strong>Reviewed By</strong></td>
                        <td>{{ auth()->user()->name }}</td>
                    </tr>

                </table>

                <div style="background:#fff4e5;border-left:5px solid #ffc107;padding:15px;margin:20px 0;">
                    <strong>Reason for Rejection</strong>

                    <p style="margin-top:10px;">
                        {{ $fundRequest->rejection_reason }}
                    </p>
                </div>

                <p>
                    Please review the comments above, make the necessary revisions,
                    and resubmit your Fund Request for approval.
                </p>

                <p>
                    If you need clarification regarding the requested changes,
                    please contact your Manager or the Executive Director before
                    resubmitting.
                </p>

                <div style="text-align:center;margin:35px 0;">
                    <a href="{{ route('fund-requests.edit', $fundRequest->id) }}"
                        style="background:#198754;
                               color:#ffffff;
                               text-decoration:none;
                               padding:12px 25px;
                               border-radius:5px;
                               display:inline-block;">
                        Edit Fund Request
                    </a>
                </div>

                <p>
                    Thank you for your cooperation.
                </p>

                <p>
                    Kind regards,<br>
                    <strong>NGO Forum on Cambodia</strong><br>
                    Fund Request Management System
                </p>

            </td>
        </tr>

        <tr>
            <td style="background:#f8f9fa;text-align:center;padding:15px;color:#777777;font-size:12px;">
                This is an automated email generated by the Fund Request Management System.
                Please do not reply to this email.
            </td>
        </tr>

    </table>

</body>

</html>
